### ISSUE TITLE
Throttle not behaving as expected - regional settings issue?

### ISSUE THREAD

**Issue by danbaz101** [DerJantob/TSW2_Controller#11]
Dear DerJantob,

Glad I found your work. Looks promissing!
Throttle is moving some, but not correctly.
Without going into the specifics already, could it be due to regional settings?
When I open the csv file, it looks like this.
![220227 csv file](https://user-images.githubusercontent.com/83304085/155889817-8a37b2cf-0fa2-418b-85d2-0c064ab54a7e.png)
.

**Comment by DerJantob** [comment]
The problem is that I have configured the trains to work with the game set to German.
If you use a different language, you should look into the `Tutorials` folder and follow the steps of "How to adapt a train to my joystick?". I will soon make a video tutorial of how to use the program, but the PDF should help for now.

I'm just a little confused as to why "äöü" is displayed so strangely on your screen.
Could you maybe send me a screenshot of
"Settings"->"Controls"->Select train:"BR112"->"Edit Controllers" and click on Brake?

But so far, thank you for your feedback!

**Comment by danbaz101** [comment]
Again would like to say I am very happy you made this as I reverted back to TS2022 in order to use my joysticks..

Looking forward to the video. I tried to follow the PDF..

The strange characters likely are caused as you are using a German version of Excel (language) and I am using an English version and US International keyboard (or something in this area...)

Here is the snip. I was driving the BR423 from Koln to Aachen. My joystick (one of them) is a Speedlink Black Widow (SL-6640-SBK).

Snip for BR112:
![220227 BR112_Controls](https://user-images.githubusercontent.com/83304085/155895225-af1b3270-3ee1-4f53-8fcc-5f420fd5b66d.png)

Appreciate your help.

**Comment by DerJantob** [comment]
I have now uploaded a video tutorial (https://www.youtube.com/watch?v=OWzzWSfhy1s)
Please let me know if you need further help, or if the tutorial helped you

**Comment by danbaz101** [comment]
Good evening,

On the BR442, when I set my lever to +50% and leave it there, then the train power slowly goes back to 5%. The lever in the cab also moves by itself accordingly.

Is this an issue with my settings
![220305 BR442_Controls](https://user-images.githubusercontent.com/83304085/156896317-755582f6-e801-443e-a1fc-6a9937c54aff.png)
?

**Comment by DerJantob** [comment]
If the program searches for the value for the throttle, but does not find one, then it presses the "Decrease power" key (so that the text appears again) until it finds the value it is looking for.
So could it be possible that you have the wrong `resolution` or one of the `text indicators` is wrong?
**Normally it is:**
- Throttle/Brake->Throttle:"Master Controller"
- Master Controller->Throttle:"Power"
- Master Controller->Brake:"Brake"

**Comment by danbaz101** [comment]
Dear DerJantob,

Today I have tried again to get it to work.

The train I drive again is the BR442.

Question 1:
I have tried to set the text indicators many times now, but when I click on Save and then  go back to it, the fields show empty again. Is that normal? Where can I see the values saved last?

Question 2:
Perhaps it helps if I understand how the program is suposed to work.
Do I understand correctly that:
1. The program reads the value of the joystick
2. Then it reads the Throttle/Brake position of the train
3. Then it uses key presses to match the train Throttle/Brake position with the position of the joystick?

Question 3:
I have two monitors. Does it make a difference on which the TSW Controller program is opened or positioned?

Main screen - used to run TSW
Resolution: 1920*1080
Windows Mode: Full screen
Screen Percentage: 100%

Second screen - NOT used to run TSW, but used to position TSW Controller
Resolution: 1280*1024

Note: while testing, when I switch to Notepad, then TSW Controller kept pressing the ddddddd

Question 4:
When testing is shows scan results. it shows it reads $A Throttle/Brake. Also shows other symbols like Brittish Pound symbol. Could there be a problem in the regional settings, keyboard settings area?

Offer: When it helps I would be glad to do a screen share session to troubleshoot.

Kind regards,
danbaz101

**Comment by danbaz101** [comment]
It seems the program sees the throttle is set to 40, but does not press a to increase power..

![image](https://user-images.githubusercontent.com/83304085/156929481-fa890493-8a7c-45bf-86c0-f99487ea9f21.png)

**Comment by DerJantob** [comment]
For your first question:
To add a new text indicator, you have to press enter.

For your second question:
That's almost correct.
1. If the joystick position changes, it instantly presses the key to match the position
2. Because reading the screen takes some amount of time, the program only reads the screen, if the joystick isn't moving for a moment
3. After that, If the positions of the game throttle and the position of the joystick do not match, then it again presses the key to match the positions

For your third question:
The program should always read the values of your main monitor.
As long as you have entered the correct resolution, it should work.

"`TSW Controller kept pressing the ddddddd`"
This is what I mean with  "`it presses the "Decrease power" key`". If the information of the simulator couldn't been read and the text vanishes, it presses "d" very short to let the information appear again

For your forth question:
This should not be a problem. As long as the program can read the important information (e.g. "Throttle/Brake 15% Brake") correctly, it doesn't matter what comes before it.

Since I am currently quite busy, I would rather not do a screen share session at the moment (but we could come back to that). Maybe it would be possible if you could send me a video of the program.

Kind regards,
Jannik

**Comment by danbaz101** [comment]
Thanks for all the answers Jannik.

Yes, I can do a video.
When I am in the sim , I cannot show the TSWController window, while still able to move the throttle.
How did you do that in your video?

Kind regards,

Daniel

**Comment by DerJantob** [comment]
I used OBS. There, you can add multiple windows or screens into the same recording

**Comment by danbaz101** [comment]
Hi there,
I have tried to make a video.
Hope you can what I am doing wrong

https://youtu.be/xiJK6MLZMjI

Regards,

Daniel

**Comment by DerJantob** [comment]
I think you misunderstood how the text indicators work.
All text indicators in the dropdown menu are "active". The program automatically detects which of the text indicators is currently displayed in the simulator. At 0:24 you have added the new indicator correctly, but instantly removed it at 0:28 by clicking on it. So if you want to add a new text indicator, just type in the name, hit return and save.

Another problem is that text indicator is not just "Throttle/Brake". At 2:46 you can see in the `scan results` that the program sometimes reads a space after and before the "/".

So just add
"Throttle/Brake"
"Throttle /Brake"
"Throttle/ Brake"
"Throttle / Brake"
to `Throttle/Brake`->`Throttle`, to make sure that all the space combinations can be detected

If you do that, it should hopefully work :)

**Comment by danbaz101** [comment]
Hi Jannik,

Thank you very much for your explanation.
I works great now!

Indeed I did not realize all in the dropdown are active. I thought I had to select one or if it did not exist create one and then add it. All clear now.

Kind regards,

Daniel

**Comment by DerJantob** [comment]
I'm glad I could help you!
