### ISSUE TITLE
BR442 - Brake settings

### ISSUE THREAD

**Issue by danbaz101** [DerJantob/TSW2_Controller#17]
Hi Jannik,

The throttle works flawlesly. Your program is really increasing the fun to play TSW2!

The brake is a bit of a combination between notches and continuous, hence I do not know how to program it.

This is how the setup is:
Release --> notch --> Hold  --> notch --> Apply 10% --> continuous --> Apply 100% --> notch --> Emergency
The working is that when a certain amount of brake pressure is set, this is kept until the lever is put back in Release position.
So, when increasing brake from release to hold --> Hold value is zero,
but when 10% or higher brake pressure was set and lever is moved back to Hold, then the Hold value is the maximum brake pressure that was reached when setting brake pressure.

This probably is quite a complex one to program...

Looking forward to hearing from you, but no rush.

Kind regards,

Daniel

**Comment by DerJantob** [comment]
Sometimes the simulator really doesn't make it easy for me. It will not work because there if you apply the brake, it displays something between "Indirect Brake" and the percentage (probably "Apply Brake" or something like that). The Program cannot handle that.
What you could do as a workaround is to add two buttons to control the brake.

**Comment by DerJantob** [comment]
Don't get confused by the next update. Unfortunately, that won't fix the problem here. I took a closer look at the issue and the program behaves very strangely when you use the master controller in combination with the brake. That's why I disabled the brake completely when using the master controller.
But I will probably deal with the problem here in the future
