### ISSUE TITLE
Control key keeps being depressed after closing TSW Controller program

### ISSUE THREAD

**Issue by danbaz101** [DerJantob/TSW2_Controller#18]
Hi Jannik,

Thanks for latest update. Helped me too.

Trying to add a button for the Tempomat (kind of cruise control). 
Switch on: Ctrl + R
Switch off: Ctrl+ R
When I got it to "work" it kept saying that Tempomat key was pressed.
When I closed the program and TSW2 and then went to google chrome and moved my scroll wheel, the page zoomed in and out without me pressing the control key. So the TSW Controller prog was still pressing the control key.
I had to log off from Windows and log back on to be able to use my keyboard again. I could not type too..

Hope that from this description you know what could be the issue, but available to provide more info as required.

Kind regards,

Daniel

**Comment by DerJantob** [comment]
It sounds like the ctrl key does not get released. Do you release the button in your shortcut?
![grafik](https://user-images.githubusercontent.com/79801484/158698567-4f83e676-2fc0-40a1-9b10-b3a61cce830c.png)

**Comment by DerJantob** [comment]
I'm really, really happy that you like the program! I'm always excited about feedback :)

I will try to add a notification if the user does an error in the input, to prevent crashes. I also like the idea that pressed keys are automatically released after closing. But it will probably take a while for the next update, because I am currently quite busy with school.
