### ISSUE TITLE
AFB

### ISSUE THREAD

**Issue by Mafreke** [DerJantob/TSW2_Controller#23]
Can you add an option for the AFB lever?

**Comment by danbaz101** [comment]
Agreed this would be very nice to have.
Trains that I drive can have four levers.
Other trains may have even more? I do not know.

**Comment by DerJantob** [comment]
Thanks for your feedback!
I'm already planning to add the AFB lever, and I'm sure it will happen soon, but first I need to fix some more bugs and take care of the release of other features :)

**Comment by DerJantob** [comment]
Hey, as you may have seen, the AFB has been moved to the "Testing" section. I've now made it, so you can add controllers yourself, so you can use throttle, brake, AFB, indirect brake, electric brake, ... basically everything.

However, it will still take some time until I can publish the update, because a lot has changed and I also still want to change some things. In addition, I then have to test a lot, so that everything runs smoothly. So it will still take a little while.

I just wanted to explain it briefly, because I already let you wait quite a long time.

**Comment by danbaz101** [comment]
Thanks Jannik,

Looking forward to it.

**Comment by DerJantob** [comment]
The version 2.0.0 has now been released. I hope you like the new version :)
