### ISSUE TITLE
Class 377 Support

### ISSUE THREAD

**Issue by LimitedEdiition** [DerJantob/TSW2_Controller#41]
I am trying to configure for the Class 377 from Brighton Main Line DLC, and the way the program is set up will not let me. The Class 377 uses a Combined Power/Brake Handle, but it is entirely notched. I am assuming to do this, we should use the Master Controller setting, but the only option is to use Continuously Variable, which is not applicable to the Class 377 as the Combined Power Handle goes from B3/B2/B1/Off/P1/P2/P3/P4.

**Comment by DerJantob** [comment]
Hey,
I get your confusion. The problem has been bothering me for a bit, I just don't know exactly how best to solve it.
You can still use this type of controller.
- Select throttle and notches.
- Add the special cases: B3=0 B2=1 B1=2 Off=3 P1=4 P2=5 P3=6 P4=7, so for the program, it is just a regular notch controller.
- Enter the number of notches (7)
- Make sure that your Joystick only goes from 0 to 100 (0=B3 and 100=P4)
You maybe need to add a long press point, because it probably has one between B1 and Off and also between Off and P1.

I hope you understand what I mean :)

**Comment by DerJantob** [comment]
I hope not, but if you still can't figure it out, I've explained it a little better here:
https://youtu.be/Sej1L0p_myo?t=2598

**Comment by baarthur** [comment]
Hi there,

I'm having the same problem with Class 375/9 (basically the same train) in TSW 3 and Win 11. I tried the solution above and the steps in the video and it didn't work. Here is how I'm configuring it:

- 8 notches
- Special cases: Emergency=0 B3=1 B2=2 B1=3 Off=4 P1=5 P2=6 P3=7 P4=8
- Controller Main Indicator: Power_/_Brake (also tried Power / Brake and Power/Brake)

When I try to find the Time Factor, the HUD text pops with the message "Power / Brake Off" (the same position it already was) but nothing happens. Then I come back to the Controller and it shows "No text indicator found!" What could it be? 

I tried to set the time factor manually but it doesn't work: when I push or pull the joystick throttle, the in-game throttle simply shakes but does not change.

Anyways, many thanks for creating this program! I hope I can find a solution.

**Comment by DerJantob** [comment]
Hey,
Other people in the DTG forum have also written about this train before. Maybe try [this](https://forums.dovetailgames.com/threads/tsw2_controller-control-tsw2-3-with-a-joystick.52402/#post-515463) solution. If it doesn't work, feel free to reach out again.

Regards
Jannik

**Comment by baarthur** [comment]
Thank you very much! I was struggling with it but now it worked with continuous setting, different time factor and your alt2 exe - later on I'll try with the latest release and see if it works. But still, I have to set the time factor manually, as it doesn't detect it automatically

If anyone wants to know, this is what worked for me:

- Master Controller
- Continuously variable 
- Joy states: -100|-76=-100 -75|-51=-75 -50|-26=-50 -25|-6=-25 -5|5=0 6|25=25 26|50=50 51|75=75 76|100=100
- Special cases: Emergency=-100 B3=-75 B2=-50 B1=-25 Off=0 Dff=0 P1=25 P2=50 P3=75 P4=100
- Time factor: 15
- Long press: from B1 & P1 to Off and from B3 to Emergency: -25|0:300 0|25:300 25|0:300 0|-25:300 -75|-100:300 -100|-75:300

**Comment by DerJantob** [comment]
I think the previous approach should work better in the end.
I have to admit that I didn't look at your previous post in detail since I don't own the train. But now I see that we actually should be able to solve the previous problem. You can actually store multiple entries in the "Main Indicator". Maybe try to add
- Power / Brake
- Power/ Brake
- Power /Brake
- Power/Brake

Otherwise, you can send me your helpfile (Settings->Help->Create helpfile). Then I can have a look at your configuration
