### ISSUE TITLE
Find Time Factor Not Working Properly Class 422

### ISSUE THREAD

**Issue by LimitedEdiition** [DerJantob/TSW2_Controller#42]
I was following along the pdf trying to determine the Time Factor (I am using the Logitech Extreme 3D Pro, so maybe the values are different than the stick that you used, and it seems like the program gets "stuck" assessing the Time Factor. I have attached a link to a YouTube video I created which might demonstrate this issue. You can see as I select Master Controller and set it to a 12% Power, it gets stuck there and then an error message pops up saying Unable to Read Numbers. I have tried running this program as administrative mode, but it fails to change. Maybe I am doing something wrong?

https://youtu.be/vF6iFEaaos8

Thank you.

**Comment by DerJantob** [comment]
OK that's weird. Is your resolution set correctly in the settings?
Another thing you can try is to position your text on a white background. Try to zoom in on the white wall on your right so that the background behind the text is just white.
The code for the "find time factor" is pretty shitty and is improved in the new version.

If it still doesn't work, you can try to calculate the time factor yourself. It's the amount of percent moved in one second. So if you move 60% (e.g. from 10% to 70%) in 1.23 seconds, you have a time factor of (60)/1.23=49. Do the same in the braking area and if they are the same type in "49" and if they are different type in "49|xx" x=the number for the braking area

**Comment by LimitedEdiition** [comment]
I haven't revisited this a while due to other things, but I believe there is some sort of interference going on with the program from something else on my PC. Likely a keyboard or something else. The entire program goes haywire when I drive something like the M7A from the Harlem Line. I will do some more troubleshooting to try to determine what is causing this.

**Comment by DerJantob** [comment]
The version 2.0.0 has now been released. The "Find Time Factor" should work much better now.
