### ISSUE TITLE
TSW2 Controller crashes to Desktop when moving throttle below 0

### ISSUE THREAD

**Issue by reslakiz** [DerJantob/TSW2_Controller#47]
Hi Jannik,

First of, thank you very much for TSW2 controller, this looks awesome.
I installed v2.0.3 today and tried to set it up with my Saitek x56 throttle.
So far I am working on assigning only one axis (Master Controller).
Now every time I move the throttle below the middle point (0) while TSW2 Controller is running, TSW2 Controller will crash to desktop.
I could not find any logs in the TSW2 Controller folder, however will attach the eventlog information that is written for every crash.

Thank you very much for your hard work on this application, if I can do anything to help you further, let me know :)

Best regards

Tobias

[tsw2contcrash.zip](https://github.com/DerJantob/TSW2_Controller/files/9883702/tsw2contcrash.zip)

**Comment by DerJantob** [comment]
Hey Tobias,

Interesting problem you got there. Could you please send me the helpfile (Settings->Help->Create helpfile) and tell me on which train the problem occurs?

Regards
Jannik

**Comment by reslakiz** [comment]
Hi Jannik,

Thank you very much for the quick reply.
Please find the file attached, the concerned train is the FLIRT.
Some more details I figured out by now: 
- the issue only occurs if I select the train and set it to active (main window)
- the issue does not occur when I set TSW2 controller to active without selecting a train
- the issue never occurs in setting up the profile etc.
- the issue occurs when finding the Time-Factor

I will play around some more later today and update you if I can figure something more out.

[TSW2Controller_HelpFile.zip](https://github.com/DerJantob/TSW2_Controller/files/9893501/TSW2Controller_HelpFile.zip)

**Comment by DerJantob** [comment]
Hi Tobias,

I found the problem. Your time factor is "53|-53" but negative numbers are not allowed there, so it should be "53|53". The time factor tells the program how long it needs to hold down a key to move a specific amount of percent in the sim. With a negative number, the program tries to hold down the key for e.g. -200ms and that causes the crash.

Did you write the minus there yourself, or did the "find time factor" do it? I hope that it was just a little error on your side, otherwise I will have to get deeper into the time factor again :)

Regards
Jannik

**Comment by reslakiz** [comment]
Hi Jannik,

Thank you very much for this insight.
Took the minus away and would you look at that, it works peachy :D

Next question, was I dumb or will I create some more hassle for you? 
Unfortunately, its option 2, ran the 'Find time factor' again, result 54|-54 (see attached screenshot).

Could it be related to my throttle having an axis from 100 (lowest position) to -100 (highest position)?

Anyway, if you like I can add you on Steam, I'm more than happy to help you with further testing.

Best regards

Tobias

![image](https://user-images.githubusercontent.com/116851095/198851008-59804ada-1fd5-4a51-8f49-ac361c9c1ed2.png)

**Comment by DerJantob** [comment]
> Could it be related to my throttle having an axis from 100 (lowest position) to -100 (highest position)?

No, the configuration does not have an effect on the time factor.

Could you maybe send me a video where you run "find time factor" again?

**Comment by reslakiz** [comment]
Hi Jannik,

Sure, can do, please find the video attached.

Best regards

Tobias

https://user-images.githubusercontent.com/116851095/199082367-f70f8ddf-63db-4534-a329-4cef55c0f745.mp4

**Comment by DerJantob** [comment]
Hey Tobias,
You're making a little mistake. In your video at 0:39, the window says to set the lever to a small value within the braking area, but you left the controller at 52% power. You should have set the controller to a position below the neutral value.

This allows the program to calculate the time factor for the throttle area and the braking area separately, because some trains have different timings for the 2 controller areas.

In my tutorial, I configured the BR423, that also has a master controller. Here you can see how to correctly get the time factor.
https://youtu.be/Sej1L0p_myo?t=2376

Kind regards
Jannik

**Comment by reslakiz** [comment]
Hi Jannik,

Thank you very much for the help :) Looks like it was only a PEBKAC after all.
When doing it properly, it works as intended. 

Say, do you have any information if TSW2 Controller also works with TSW3?

Best regards,

Tobias

**Comment by DerJantob** [comment]
> Thank you very much for the help :) Looks like it was only a PEBKAC after all.
When doing it properly, it works as intended.

That's great news! I was already afraid that I would have to fight my way through my chaos code again :)
Just for understanding and because I saw what you had written before ;), the time factor has nothing to do with the physical joystick and only deals with the controller in the simulator. Its purpose is to tell the program how long it needs to hold down a key to move the sim controller a specific amount of percent.

> Say, do you have any information if TSW2 Controller also works with TSW3?

I myself do not have TSW3, but I have heard from others that the program runs without problems with TSW3. But that only applies to the Steam version. Someone else has tested the program with the Xbox Gamepass version and there the program does not work at all, because, for whatever reason, simulated keystrokes are not recognized there.

Kind regards
Jannik

**Comment by reslakiz** [comment]
> Just for understanding and because I saw what you had written before ;), the time factor has nothing to do with the physical joystick and only deals with the controller in the simulator. Its purpose is to tell the program how long it needs to hold down a key to move the sim controller a specific amount of percent.

Thank you, that was indeed my misunderstanding, now it works perfectly fine. :)

> I myself do not have TSW3, but I have heard from others that the program runs without problems with TSW3. But that only applies to the Steam version. Someone else has tested the program with the Xbox Gamepass version and there the program does not work at all, because, for whatever reason, simulated keystrokes are not recognized there.

Sounds like some weird UWP magic maybe - but good to know it will work with the Steam version if I get it some time.

Thank you very very much for your superb and friendly support, closing this now as it was my fault all along the way. ;)

Best regards

Tobias

**Comment by DerJantob** [comment]
No problem. Glad I could help you!
