### ISSUE TITLE
BR403 - AFB trouble

### ISSUE THREAD

**Issue by danbaz101** [DerJantob/TSW2_Controller#54]
Hello Jannik,

This a question regarding AFB lever for BR 403 train.

1. Pls see first snip. Top right says ->18. Where does it come from. How can I manipulate?
2. Pls see the second snip. I moved lever up a bit and left it there. The program moved the lever in sim up and back three times and would have continued this probably. Have I done something wrong?

Kind regards,

Daniel

![image](https://github.com/DerJantob/TSW2_Controller/assets/83304085/d4329b2c-c01f-4bd3-8684-323001a0ef53)

![image](https://github.com/DerJantob/TSW2_Controller/assets/83304085/2b09478f-4c2e-46c3-98a8-80040a41f6aa)

**Comment by DerJantob** [comment]
That's pretty weird. It is as if the program does not detect your controller, but it obviously does. 
Here is an example what the "-> 18" should be:

Each number between the arrows show different stages of the conversion of your joystick state. So in my case, the 3 is the raw value, the 48 is the conversion that 100 equals 0 and -100 equals 100. The 16 is the conversion into the different notches
![grafik](https://github.com/DerJantob/TSW2_Controller/assets/79801484/d1e58921-aa54-4078-afea-268efb6f2dee)

I'm a bit lost now, as the code for the green bar depends on the same code as for the top left window. You could maybe try to reinstall the program once. Your configuration should not be lost when you uninstall, but you should make a backup of it to be on the safe side.

Regards
Jannik

**Comment by danbaz101** [comment]
Added later: Thanks for your explanation about how to read the coding above the green bar and the suggestion to re-install the program. I have reinstalled, but this has not solved the problem.

My Joystick where it shows wrong is a CH Products - Flight Sim Yoke. Is there anything on my end that I could test/check?
When I use my other joystick - Speedlink - Black Widow - it shows correctly as in your snip.

When I use the black widow and just push the lever full forward and leave it there, in sim the lever is pushed forward about half travel and then pulled back, then it starts again.
It says move from 210 to 33. Seems it is comparing apples to eggs (km to notches)??

![image](https://github.com/DerJantob/TSW2_Controller/assets/83304085/57f492d5-ed2c-47d2-82b6-0fd951144e3e)

**Comment by DerJantob** [comment]
Hey,
I did a little testing on my end and the issue regarding the green bar and the text above could potentially be fixed. I will send you a pre-release version (also containing other improvements). It would be great, if you could test it for me, and check if this fixes your problems.

The thing you mentioned regarding the AFB, you have to add a lot more special cases. The problem is, that my program does not know, which steps the AFB takes, so it just assumes that the km/h value is equal to the notch. Here is an example for the BR143:
Convert special cases:
`Aus=0 Ein=1 100_km/h=11 110_km/h=12 120_km/h=13 10_km/h=2 20_km/h=3 30_km/h=4 40_km/h=5 50_km/h=6 60_km/h=7 70_km/h=8 80_km/h=9 90_km/h=10`
So in my case, I tell the program that e.g. the position 80km/h is equal to the notch 9. For your case, you would need to expand this list or even adapt the numbers. I hope you understand what I mean :)

Here is the pre-release:
[TSW2_Controller_PreRelease_1.zip](https://github.com/DerJantob/TSW2_Controller/files/11582037/TSW2_Controller_PreRelease_1.zip)


Regards
Jannik

**Comment by danbaz101** [comment]
Thanks Jannik,

I will test tomorrow.

**Comment by danbaz101** [comment]
Hello Jannik,

The new version solved the problem! Thank you very much!

The AFB now also works as expected. 
For BR 403 is use this as special cases (in case somebody wants to copy):
Okm/h=0 0km/h=0 10km/h=1 20km/h=2 30km/h=3 40km/h=4 50km/h=5 60km/h=6 70km/h=7 80km/h=8 90km/h=9 100km/h=10 110km/h=11 120km/h=12 130km/h=13 140km/h=14 150km/h=15 160km/h=16 170km/h=17 180km/h=18 190km/h=19 200km/h=20 210km/h=21 220km/h=22 230km/h=23 240km/h=24 250km/h=25 260km/h=26 270km/h=27 280km/h=28 290km/h=29 300km/h=30 310km/h=31 320km/h=32 330km/h=33

I do have a question on the Brake for which I will open a separate ticket.

Kind regards,

Daniel
